version: "3.8"
services:
  # client:
  #   stdin_open: true # what does this do?
  #   build:
  #     context: './service_client_new'  
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./service_client_new/:/usr/src/app
  #     - ./service_client_new/app/node_modules

  nsp_backend:
    container_name: nsp_backend
    image: francescoxx/nsp-template:0.0.2
    build:
      context: ./service_server
    ports:
      - "3001:3001"
    environment:
      - MICROSERVICE_PORT=3001
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=nsp_database
      - PGHOST=nsp_db # NAME OF THE SERVICE
    depends_on:
      - nsp_db
    volumes:
      - ./service_server/:/usr/src/app
      - ./service_server/app/node_modules

  nsp_db:
    container_name: nsp_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nsp_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}